version: "3.8"
name: abilimpus-development
services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=webserver
      - POSTGRES_PASSWORD=123456
      - PGDATA=/var/lib/postgresql/data/pg-data
      - POSTGRES_DB=development
    expose:
      - 5432
    volumes:
      - ./data/dev:/var/lib/postgresql/data/pg-data:rw
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 10s
      retries: 3

  web:
    develop:
      watch:
        - path: .
          action: sync
          target: /project
    env_file:
      - .env.development
    build:
      target: dev
      args:
        - ENV=development
    expose:
      - "80:80"
    ports:
      - "5555:5555"
#      - "80:80"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx:rw
      - ./storage:/storage:rw
    depends_on:
      - web